name: "AnchorKG"
n_gpu: 1
data_loader:
    batch_size: 64
    shuffle: true
    num_workers: 1

data:
  datapath: "/data"
  savepath: "/out"

  train_news : "./data/train/news.tsv"
  train_behavior : "./data/train/behaviors.tsv"
  valid_news : "./data/valid/news.tsv"
  valid_behavior : "./data/valid/behaviors.tsv"
  warm_up_train_file: "/warmup_data_train.tsv"
  warm_up_test_file: "/warmup_data_test.tsv"
  train_file: "/item2item/train.tsv"
  val_file: "/item2item/valid.tsv"
  test_file: "/item2item/test.tsv"
  doc_feature_entity_file: "/doc_feature_entity.tsv"
  doc_feature_embedding_file: "/doc_feature_embedding.tsv"
  kg_file: "./data/kg/wikidata-graph/triple2id.txt"
  entity_embedding_file: "./data/kg/wikidata-graph/entity2vecd100.vec"
  relation_embedding_file: "./data/kg/wikidata-graph/relation2vecd100.vec"
  entity2id_file: "./data/kg/wikidata-graph/entity2id.txt"
  relation2id_file:  "./data/kg/wikidata-graph/realtion2id.txt"


model:
  doc_embedding_size: 768
  embedding_size: 128
  news_entity_num: 20
  alpha1: 0.9 # weight of recommendation reward and reasoning reward
  alpha2: 0.9 # weight of immediate reward
  beta: 0.2
  topk: [5,3,2] # field sizes
  gamma: 0.9

trainer:
  epochs: 100
  warm_up: False
  train_neg_num: 4
  save_dir: "./out/saved/"
  save_period: 1
  early_stop: 3
  monitor: "val_auc"
  verbosity: 2

optimizer:
  type: "Adam"
  lr: 0.00002
  weight_decay: 0.000001
  amsgrad: true